version: "3.8"
services:
       client:
           tty: true
           build:
            dockerfile: Dockerfile
            context: ./client
           networks:
              - mongo-yolo-network
           ports:
              - "3000:3000"  
       backend:
           tty: true
           depends_on:
              - mongo
           build:
            dockerfile: Dockerfile
            context: ./backend
           environment:
              - MONGODB_URI=mongodb://mongo
           networks:
              - mongo-yolo-network      
            
       mongo:
             container_name: mongo
             image: mongo:latest
             command: mongod --port 27017 --bind_ip_all
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'
             networks:
               - mongo-yolo-network
volumes:
      data:
networks:
      mongo-yolo-network:               