version: "3.8"
services:
       client:
           tty: true
           image: aleedaf/yolo:client-1.0.0
           build:
            dockerfile: Dockerfile
            context: ./client
           networks:
              - mongo-yolo-network
           ports:
              - "3000:3000"  
       backend:
           tty: true
           image: aleedaf/yolo:backend-1.0.0
           depends_on:
              - mongo
           build:
            dockerfile: Dockerfile
            context: ./backend
           environment:
              - MONGODB_URI=mongodb://mongo
           networks:
              - mongo-yolo-network
           ports:
              - "3001:3001"         
            
       mongo:
             container_name: mongo
             restart: always
             image: mongo:latest
             command: mongod --port 27017
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'
             networks:
               - mongo-yolo-network
volumes:
      data:
networks:
      mongo-yolo-network:               